name = "MultipleViewGeometry"
uuid = "7cb2d126-0d79-4d10-9b32-74e21e85bc60"
authors = ["Ashwani Rathee"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
